softwareunderground/awesome-open-geoscience

README.md
Seismic data processing suite https://github.com/ahay
=> Madagascar

README.md
added striplog to wells,
added a section for 'platforms', 
and moved mapping tool to geospatial
=> moved one thing to a better section, added a section, and added a tool

README.md
https://www.digitalrocksportal.org/
=> Digital rock portal

README.md
=> Update a python svg icon.

README.md
=> Geochemistry added

README.md
=> Use full name for "Fatiando a Terra"

README.md
I have added Open source GIS software and USGS software for modeling of subsurface flow
=> QGIS and Modflow added

README.md
Added "World Stress Map" under Data Repositories, along with a link and a brief description.
=> Add World Stress Map

README.md
Added "Stress2Grid" link to MATLAB script, along with description.
=> Add the "Stress2Grid" MATLAB script

README.md
Added in two sources of government-provided open petroleum geoscience data.
=> Added in two sources of government-provided open petroleum geoscience data

README.md
RINGMesh is a C++ open-source platform for manipulating meshes of geological models. RINGMesh is neither a geomodeler nor a mesh generation tool, but it can be used to develop geomodeling applications, such as meshing and numerical simulation tools.
=> Adding RINGMesh platform

README.md
Since Resqml can deal with data from seismic to simulation, I created the category "Data Management".
=> Add Fesapi link

README.md
Added mplStereonet in a new section for structural geology
=> Added mplStereonet

README.md
Landlab is an open source surface process modelling environment.
=> Add Landlab to readme.md

README.md
As mentioned in #43 
Could someone please double check this to make sure this link is correct.
=> Fix colorcet link

README.md
The title case is a personal preference. I can revert it back if wanted.
Fixes #43
=> Add a Travis badge and use title case in README

.github/PULL_REQUEST_TEMPLATE.md, contributing.md
Add the checklist for new contributions to the PR template so that people know to fill it out before submitting.
=> Tweaks to contributing guide and a PR template

README.md
Project name: pyGeoPressure
Project website/repository:
https://pygeopressure.readthedocs.io/en/latest/
https://github.com/whimian/pyGeoPressure
License:
MIT
- [ x ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x ] Searched the existing entries to make sure this is not a duplicate.
- [ x ] Added the link to the bottom of the relevant category.
- [ x ] Contains only a single addition (make separate PRs if adding more than one).
- [ x ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.
- [ x ] Created a new category only if necessary.
- [ x ] Checked spelling and grammar.
- [ x ] Removed trailing whitespace (set your text editor to do this automatically).
=> add pyGeoPressure

README.md
Fixed a lot of formats all over the place.
=> Fix all format

README.md
Project name: Modelr.io
Project website/repository:
modelr.io
https://github.com/agile-geoscience/modelr
License:
Apache License, Version 2.0
- [ x ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x ] Searched the existing entries to make sure this is not a duplicate.
- [ x ] Added the link to the bottom of the relevant category. (Readded at same location)
- [ x ] Contains only a single addition (make separate PRs if adding more than one).
- [ x ] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.
- [ x ] Created a new category only if necessary.
- [ x ] Checked spelling and grammar.
- [ x ] Removed trailing whitespace (set your text editor to do this automatically).
=> Modelr.io Reinclusion

README.md
Project name: Wikipedia list of free geophysical software
Project website/repository: https://en.wikipedia.org/wiki/Comparison_of_free_geophysics_software
=> Add Wikipedia list

README.md
Project name: empymod
Project website/repository: https://empymod.github.io
License: Apache v2
=> Add empymod

README.md
Project name: PyLops
Project website/repository: https://pylops.readthedocs.io
License: LGPL 3.0
=> Add PyLops

.github/PULL_REQUEST_TEMPLATE.md
Make sure the formatting is even more uniform and sort by priority.
=> Add stuff to the PR List

README.md
=> Link Fixes Fatiando and PhreeQC

README.md
Project name: TerraNubis
Project website/repository:
License:
- [ x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x] Added the link to the bottom of the relevant category.
- [ x] Add icon from the `media/icon/` folder if applicable (like `![Python](media/icon/python.png)` ).
- [ x] Created a new category only if necessary.
- [ x] Removed trailing whitespace and periods.
- [ x] Confirm the dash – is not a minus -.
- [ x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.
=> Added TerraNubis (new OSR)

README.md
As discussed in #60, this would a cross reference to the new [awesome-open-climate-science](https://github.com/pangeo-data/awesome-open-climate-science) list.
=> link to awesome open climate science

README.md
Project name: GeoStats.jl
Project website/repository: https://github.com/juliohm/GeoStats.jl
License: ISC
=> Add GeoStats.jl

README.md
Project name: Quantarctica
Project website/repository: http://quantarctica.npolar.no/
License: [Creative Commons 4.0](http://quantarctica.npolar.no/about.html#tou)
=> added Quantarctica

README.md
Project name: `vista`
These changes update the descriptions of `vista` based software in accordance with its recent name change.
=> Change vista descriptions

README.md
Adding GeostatsPy to the List of Open Source Geostatistics Software
Project name: GeostatsPy
Project website/repository: https://github.com/GeostatsGuy/GeostatsPy
License: MIT
=> Add GeostatsPy

README.md
=> Update PyVista links

README.md
Project name: RGPR
Project website/repository: https://github.com/emanuelhuber/RGPR
License: GNU General Public License v3.0
=> Add a ground-penetrating radar software

README.md
Project name: readgssi
Project website/repository: https://github.com/iannesbitt/readgssi
License: AGPL v3
=> Add readgssi

README.md
Project name: Pangeo
Project website/repository: https://pangeo.io
License: Various packages with Open-Source licences
=> Add a link to the Pangeo project

.github/PULL_REQUEST_TEMPLATE.md, awesome.md
Added all of the following and edited the text to be more "awesome focused"
Open Licensing, Software, Software, Unacceptable, Software Documentation, Readme, Installation Instructions, Examples and Tutorials, API Documentation, Software Tests, Datasets, Dataset Documentation, Download Instructions, Publications and Cheat Sheets, Project Community Guidelines
=> Initial Formulation of our Awesome Manifesto

README.md
Project name:
pyrolite
Project website/repository:
https://github.com/morganjwilliams/pyrolite
License:
[CSIRO BSD/MIT](https://github.com/morganjwilliams/pyrolite/blob/master/LICENSE)
=> Add pyrolite to geochemistry section

README.md
This PR is addressing Issue https://github.com/softwareunderground/awesome-open-geoscience/issues/94.
Project name: GeoStat-Framework
Project website/repository: https://github.com/GeoStat-Framework
License: LGPL and MIT
=> Add the GeoStat-Framework

README.md
Adding a PHP package for the GIS section
Project name: GeoPHP
Project website/repository: https://github.com/phayes/geoPHP
License:  This library is open-source and dual-licensed under both the Modified BSD License and GPLv2.
=> Adding a new GIS package

README.md
Fix description and formatting for #96
=> Fix description for GeoPHP

README.md
Project name: awesome-coastal
Project website/repository: https://github.com/chrisleaman/awesome-coastal
License: CC0
=> Add awesome-coastal to related awesome category

README.md
This is a refork of #105 
Project name: PetroPy
Project website/repository: [GitHub](https://github.com/toddheitmann/PetroPy)
License: MIT License
PetroPy can be installed with pip to perform petrophysical calculations, output las files, and log images. It's fully open sourced.
=> Add Petropy Reforked for TravisCI Rerun

README.md
Project name: OpendTect-Plugins
Project website/repository: [WMPlugins](https://github.com/waynegm/OpendTect-Plugins)
License: GPL3
=> Add opendtect-plugins link

README.md
Project name: The Basic Model Interface (BMI)
Project website/repository: https://github.com/csdms/bmi
License: MIT
=> Add link to the Basic Model Interface (BMI)

README.md
Project name: Python Modeling Toolkit (PyMT)
Project website/repository: https://github.com/csdms/pymt
License: MIT
=> Add link to PyMT

README.md
OpenGeode is now also providing a Python binding.
=> Update OpenGeode languages

README.md
This PR adds back the Digital Rocks Portal, removed in #76 and recorded in issue #77. Closes #77.
Project name: Digital Rocks Portal
Project website/repository: https://www.digitalrocksportal.org/
License:
=> add back the Digital Rocks Portal, removed in #76 and recorded in issue #77

.github/PULL_REQUEST_TEMPLATE.md
Update the pr template to include clear section delineation and other potential improvements.
I think that with these changes, it is simpler for the submitter to see what they must "check off", and easier for reviewers to see which boxes need to be checked off for that submission. In particular, this will make reviewing updates and fixes extremely easy.
I also fixed a link to the title-casing website, that one seemed dead so I just added a general description reference.
The new PR template would be (as code):
```
__License:__
```
and rendered:
---------
__License:__
=> Update the pr template to include clear section delineation and other potential improvements

README.md
Project name: SHEMAT-Suite
Project website/repository: https://git.rwth-aachen.de/SHEMAT-Suite/SHEMAT-Suite-open
License: MIT
=> Add SHEMAT-Suite

README.md
Project name: rsudp
Project website/repository: https://github.com/raspishake/rsudp
License: [GPL v3](https://github.com/raspishake/rsudp/blob/master/LICENSE)
=> adding rsudp

README.md
=> clean XTgeo entry

README.md
There is a LOT of data here and continued additions from multiple work streams as they complete.  It has grown impressively in just over a year.  Includes a 'make your own random forest geochem model function' even.  Very impressive.
__License:__
=> Add Geoscience Australia Portal

README.md
SeismicZFP
https://github.com/equinor/seismic-zfp
__License:__
LGPLv3
=> Add seismic-zfp

README.md
Addition to Data Repositories section.
GSQ Open Data portal, with link to site and to background organisational GitHub page.
__License:__
=> Update README.md - Addition of GSQ Open Data Portal

README.md
Australian state geoscience portal, including web services access.
__Project name:__SARIG
__Project website/repository:__https://map.sarig.sa.gov.au/
__License:__
- [x ] Project is [`certified awesome`](awesome.md)
- [ x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x] Added the link to the bottom of the relevant category.
- [ x] Removed trailing whitespace and periods.
- [ x] Easily accessible
- [ x] Comprehensive and widely appealing
=> Add SARIG - South Australian Resources Information Gateway

README.md
__Project name:__ SEG Open Data Catalog
__Project website/repository:__ https://wiki.seg.org/wiki/Open_data
__License:__ Various
__Submission type:__ New Data Repository
=> Add SEG Open Data Catalog

README.md
=> Added dlisio to the well log section

README.md
Awesome-Earth-Artificial-Intelligence list
github.com/ESIPFed/Awesome-Earth-Artificial-Intelligence
New Awesome List
- [ x] Project is [`certified awesome`](awesome.md)
- [ x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x ] Added the link to the bottom of the relevant category.
- [ x] Created a new category only if necessary.
- [x ] Add icon from the `media/icon/` folder if applicable (e.g., `![Python](media/icon/python.png)` ).
- [x ] Checked spelling and grammar.
- [ x] Removed trailing whitespace and periods.
- …
=> ESIP ML cluster's new Awesome List on Artififical intelligence in Earth Sciences

README.md
=> added NOSEpick radar interpretation GUI to readme

README.md
=> NOSEpick renamed to RAGU

README.md
=> add volve dataset

README.md
=> update RAGU description

README.md
pysgems
https://github.com/robinthibaut/pysgems
__License:__
MIT License
"New Software Project"
- [x ] Project is [`certified awesome`](awesome.md)
- [x ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x ] Searched the existing entries to make sure this is not a duplicate.
- [x ] Contains only a single addition (make separate PRs if adding more than one).
- [x ] Added the link to the bottom of the relevant category.
- [x ] Created a new category only if necessary.
- [x ] Add icon from the `media/icon/` folder if applicable (e.g., `![Python](media/icon/python.png)` ).
- [x ] Checked spelling and grammar.
- [x ] Removed trailing whitespace and periods.
- [x ] Confirm the …
=> Added pysgems in the Geostatistics list

README.md
SeisComp and RedPy added, they are serious awesome software! Check it out!
__License:__
=> Just added some soft to the Readme. They are awesome!

README.md
__Project name:__  ipyleaflet
__Project website/repository:__ https://github.com/jupyter-widgets/ipyleaflet
__License:__ MIT
=> Add ipyleaflet

README.md
wellpathpy
https://github.com/Zabamund/wellpathpy
__License:__
LGPL-3.0
=> Proposing to add wellpathpy to the list

README.md
PyGMI is Python Geoscience Modelling and Interpretation which was developed at  Council for Geoscience (Geological Survey of South Africa). 
It has the following key features: 
Magnetic and Gravity 3D forward modelling.
Cluster Analysis, including use of scikit-learn libraries.
Routines for cutting, reprojecting and doing simple modifications to data.
Convenient display of data using pseudo-colour, ternary and sunshaded representation.
MT processing and 1D inversion using MTpy.
Gravity processing.
Seismological functions for SEISAN data.
Remote sensing ratios and improved imports.
__Project name:__ PyGMI 
__Project website/repository:__ https://github.com/Patrick-Cole/pygmi
__License:__ GPL-3.0 License
=> Add PyGMI Software in list

README.md
Solves issue #136
__Project name:__ Pyrocko
__Project website/repository:__   https://git.pyrocko.org/pyrocko/pyrocko
__License:__
__Submission type:__ Update existing entry
=> Added updated link of Pyrocko

README.md
A standalone tool to create simplified/lighweight surfaces from dense point cloud data. Its best use cases are very large datasets where traditional methods such as delaunay are not viable. This functionality is rare even in proprietary software packages, and even then usually requires multiple steps to achieve this kind of result.
vtk_triangulate_points
https://github.com/pemn/vtk_triangulate_points
__License:__
Apache 2.0
=> vtk_triangulate_points

README.md
This PR only updates the current description of the project `dlisio`. As of v0.3.0 dlisio also parses and reads the Well Log Format: Log Interchange Standard (LIS)
=> Update description of dlisio to include LIS

README.md
Proposing to add Webviz to the list, along with Webviz-subsurface.
Webviz+Webviz-subsurface
https://github.com/equinor/webviz-subsurface/
__License:__
MIT for webviz-config, GPLv3 for webviz-subsurface
=> Add Webviz

README.md
__Project name:__ pyVDS
__Project website/repository:__ https://github.com/equinor/pyvds
__License:__ Apache 2.0
=> Propose adding pyVDS

README.md
__Project name:__ pyZGY
__Project website/repository:__ https://github.com/equinor/pyzgy
__License:__ Apache 2.0
=> Propose adding pyZGY

README.md
__Project name: SciKit-gstat
__Project website/repository: https://github.com/mmaelicke/scikit-gstat
__License: MIT
__Submission type: New Software Project
=> Add link to SciKit-gstat

README.md
G2S
https://gaia-unil.github.io/G2S/
https://github.com/GAIA-UNIL/G2S
__License:__
GPLV3
- [ x] Project is [`certified awesome`](awesome.md)
- [x ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x ] Contains only a single addition (make separate PRs if adding more than one).
- [ x] Added the link to the bottom of the relevant category.
- [ x] Created a new category only if necessary.
- [ x] Add icon from the `media/icon/` folder if applicable (e.g., `![Python](media/icon/python.png)` ).
- [ x] Removed trailing whitespace and periods.
- [ x] …
=> Add of G2S as MPS framework

README.md
__Project name:__ localtileserver
__Project website/repository:__ https://github.com/banesullivan/localtileserver
__License:__ MIT
=> Add localtileserver

README.md
A thermobarometry tool that can be added to the geochemistry section.
__Project name:__Thermobar
__Project website/repository:__ https://github.com/PennyWieser/Thermobar
__License:__
- [ x] Project is [`certified awesome`](awesome.md)
- [x ] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [ x] Add icon from the `media/icon/` folder if applicable (e.g., `![Python](media/icon/python.png)` ).
- [x ] Removed trailing whitespace and periods.
- [ x] Confirm the dash – is not a minus -.
- [ x] Used …
=> Adding Thermobar

README.md
PyFWI can be used to perform FWI and time-lapse FWI
__Project name:__ 
PyFWI
https://pyfwi.readthedocs.io/en/latest/  
https://github.com/AmirMardan/PyFWI
__License:__ 
[GPL-3.0 license](https://github.com/AmirMardan/PyFWI/blob/main/LICENSE)
"New Software Project"
- [ x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x ] Added the link to the bottom of the relevant category.
- [ x] Add icon from the `media/icon/` folder if applicable (e.g., `![Python](media/icon/python.png)` ).
- [ x] Link the code …
=> PyFWI is added

README.md
__Project name:__ Pyinterpolate
__Project website/repository:__ https://github.com/DataverseLabs/pyinterpolate
__License:__ BSD-3-Clause
=> Update readme - pyinterpolate package

README.md
Pastas is an awesome open-source package for the analysis of groundwater time series.
__Project name:__ Pastas
__Project website/repository:__ https://github.com/pastas/pastas
__License:__ MIT
=> Add Pastas to README.md

README.md
Add stress_state_plot package for visualization of stress state to Structural Geology section of README.md
__Project name:__  stress_state_plot
__Project website/repository:__ https://github.com/mkondratyev85/stress_state_plot
__License:__ MIT
=> Add stress_state_plot to README

README.md
=> Fix Markdown syntax for one of the links

README.md
Add LoopStructural & OccamPy, Sorted by alphabetical order &  Add a dot at the end of the sentence
=> Add LoopStructural & OccamPy, Sorted by alphabetical order &  Add a dot at the end of the sentence

README.md
__Project name:__ Razorback
__Project website/repository:__ https://github.com/brgm/razorback
__License:__ [GPL-3.0 license](https://github.com/BRGM/razorback/blob/master/LICENSE) 
=> adding Razorback in Geophysics section

README.md
__Project name:__ GemGIS
__Project website/repository:__ https://github.com/cgre-aachen/gemgis
__License:__ https://github.com/cgre-aachen/gemgis/blob/main/LICENSE
=> Adding GemGIS to the geospatial section of the readme

README.md
__Project name:__ Macrostrat
__Project website/repository:__ https://macrostrat.org, https://macrostrat.org/api
__License:__ Creative Commons
__Submission type:__ New Data Repository
=> Add Macrostrat to datasets

README.md
Add Costa model to data repositories
__Project name:__ COSTA MODEL: Hierarchical carbonate reservoir benchmarking case study
__Project website/repository:__ https://researchportal.hw.ac.uk/en/datasets/costa-model-hierarchical-carbonate-reservoir-benchmarking-case-st
__License:__ CC BY
__Submission type:__ New Data Repository
=> Costa Model: awesome data repository

README.md
Geospatial Data Science with Julia
https://juliaearth.github.io/geospatial-data-science-with-julia
__License:__
Creative Commons
Open books
=> Add open books section

README.md
Adds a DOI badge as requested in issue: https://github.com/softwareunderground/awesome-open-geoscience/issues/202
=> added DOI badge

README.md
adding synthoseis package to seismic section.
this package, which was created and open-sourced by Shell, generates synthetic seismic data based off a given rock properties model.
__Project name:__ Synthoseis
__Project website/repository:__ https://github.com/sede-open/synthoseis
__License:__ MIT License
=> Update Seismic tools section in README.md with Synthoseis package

README.md
gstlearn is the new cross-platform Geostatistics C++ library proposed by [MINES Paris - PSL University](https://www.minesparis.psl.eu/). It offers to users all famous Geostatistical methodologies developed and/or invented by the Geostatistic Team of the [Geosciences Research Center](https://www.geosciences.minesparis.psl.eu/).
gstlearn comes in various forms: A C++ library, a Python package and an R package.
__Project name:__ 
gstlearn
__Project website/repository:__ 
Github repo : https://github.com/gstlearn/gstlearn
Official website : https://gstlearn.org
__License:__
C++ Library : BSD 3-clause
Python Package : BSD 3-clause
R Package : GPL v3
=> Propose gstlearn to Awesome list

awesome.md
The original link to GNU Lesser General Public License on Awesome.md is dead. Now only pages to versioned versions of that license exist. 
This PR therefore changes the link to be for the page of: GNU Lesser General Public License version 3
Basically same thing but version 3
=> Update dead link

README.md
- Digitize Heatmap
__Project website/repository:__ 
- [https://github.com/RyanFu008/digitize-heatmap](https://github.com/RyanFu008/digitize-heatmap)
__License:__ 
- MIT License
- New Software Project
- [ x Used [title-casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) (AP style) for project name.
- This seems difficult to do - I would greatly appreciate feedback on this point
=> Digitize Heatap

README.md
- Project Pythia
- https://projectpythia.org/
__License:__
- Code: Apache 2.0
- Non-code: [Creative Commons BY 4.0 (CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
- New Tutorial or Cheat Sheet
=> Project Pythia

README.md
- Awesome Open Hydrology - Awesome list of resources and tools related to hydrology
- https://github.com/Open-Environmental-Science/awesome-open-hydrology
__License:__
- CC0 1.0 Universal
- New Related Awesome
=> Awesome Open Hydrology

README.md
Add https://github.com/deepfield-team/DeepField to the list of reservoir engineering tools
__Project name:__ DeepField
__Project website/repository:__https://github.com/deepfield-team/DeepField
__License:__MIT
=> add link to DeepField
